language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-scalatron' ]; then cd .. && eval "mv $currentfolder generator-scalatron" && cd generator-scalatron; fi

